
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int right_parenthesis = 3;
  public static final int let_keyword = 23;
  public static final int equal_operator = 41;
  public static final int char_literal = 53;
  public static final int not_operator = 46;
  public static final int right_block = 5;
  public static final int elseif_keyword = 48;
  public static final int float_keyword = 17;
  public static final int exit_when_keyword = 28;
  public static final int decrement_operator = 14;
  public static final int comma_keyword = 26;
  public static final int identifier = 55;
  public static final int not_equal_operator = 42;
  public static final int greater_equal_operator = 39;
  public static final int division_operator = 9;
  public static final int left_parenthesis = 2;
  public static final int modulo_operator = 11;
  public static final int float_literal = 51;
  public static final int and_operator = 45;
  public static final int break_keyword = 36;
  public static final int assignment_operator = 15;
  public static final int int_division_operator = 10;
  public static final int or_operator = 44;
  public static final int multiplication_operator = 8;
  public static final int EOF = 0;
  public static final int increment_operator = 13;
  public static final int do_keyword = 34;
  public static final int error = 1;
  public static final int return_keyword = 35;
  public static final int less_operator = 38;
  public static final int output_keyword = 25;
  public static final int int_keyword = 16;
  public static final int for_keyword = 30;
  public static final int delimiter = 43;
  public static final int string_keyword = 20;
  public static final int minus_operator = 7;
  public static final int power_operator = 12;
  public static final int int_literal = 50;
  public static final int downto_keyword = 33;
  public static final int step_keyword = 31;
  public static final int bool_keyword = 18;
  public static final int principal_keyword = 22;
  public static final int string_literal = 54;
  public static final int to_keyword = 32;
  public static final int less_equal_operator = 40;
  public static final int loop_keyword = 27;
  public static final int char_keyword = 19;
  public static final int void_keyword = 21;
  public static final int else_keyword = 49;
  public static final int input_keyword = 24;
  public static final int bool_literal = 52;
  public static final int end_loop_$_keyword = 29;
  public static final int greater_operator = 37;
  public static final int decide_of_keyword = 47;
  public static final int plus_operator = 6;
  public static final int left_block = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "left_parenthesis",
  "right_parenthesis",
  "left_block",
  "right_block",
  "plus_operator",
  "minus_operator",
  "multiplication_operator",
  "division_operator",
  "int_division_operator",
  "modulo_operator",
  "power_operator",
  "increment_operator",
  "decrement_operator",
  "assignment_operator",
  "int_keyword",
  "float_keyword",
  "bool_keyword",
  "char_keyword",
  "string_keyword",
  "void_keyword",
  "principal_keyword",
  "let_keyword",
  "input_keyword",
  "output_keyword",
  "comma_keyword",
  "loop_keyword",
  "exit_when_keyword",
  "end_loop_$_keyword",
  "for_keyword",
  "step_keyword",
  "to_keyword",
  "downto_keyword",
  "do_keyword",
  "return_keyword",
  "break_keyword",
  "greater_operator",
  "less_operator",
  "greater_equal_operator",
  "less_equal_operator",
  "equal_operator",
  "not_equal_operator",
  "delimiter",
  "or_operator",
  "and_operator",
  "not_operator",
  "decide_of_keyword",
  "elseif_keyword",
  "else_keyword",
  "int_literal",
  "float_literal",
  "bool_literal",
  "char_literal",
  "string_literal",
  "identifier"
  };
}

